package examples.inlinedAggregatedObjects.models

import com.fasterxml.jackson.`annotation`.JsonProperty
import javax.validation.Valid
import kotlin.collections.List

/**
 * A chat completion message generated by the model.
 */
public data class ReferencedObjectWithArrayInlining(
  @param:JsonProperty("annotations")
  @get:JsonProperty("annotations")
  @get:Valid
  public val annotations: List<ReferencedObjectWithArrayInliningAnnotations>? = null,
)
